// port-lint: source serde/src/private/mod.rs
package io.github.kotlinmania.serde.`private`

<<<<<<< HEAD
// The upstream Rust module is a re-export surface for code generated by serde_derive.
// Kotlin has no conditional compilation; this file preserves the same "private facade"
// intent by collecting the names that generated code expects to refer to.

// #[cfg(not(no_serde_derive))] pub mod de;
// #[cfg(not(no_serde_derive))] pub mod ser;
//
// These become sibling Kotlin files in the same package, translated 1:1 from:
// - `serde/src/private/de.rs`
// - `serde/src/private/ser.rs`

// pub use crate::lib::clone::Clone;
public fun interface Clone<T> {
    public fun clone(): T
}

// pub use crate::lib::convert::{From, Into, TryFrom};
public fun interface From<T, out R> {
    public fun from(value: T): R
}

public fun interface Into<in T, R> {
    public fun into(value: T): R
}

public fun interface TryFrom<T, out R> {
    public fun tryFrom(value: T): Result<R>
}

// pub use crate::lib::default::Default;
public fun interface Default<out T> {
    public fun default(): T
}

// pub use crate::lib::fmt::{self, Formatter};
public object fmt

public class Formatter

// pub use crate::lib::marker::PhantomData;
public class PhantomData<T>

// pub use crate::lib::option::Option::{self, None, Some};
public sealed interface Option<out T> {
    public data class Some<out T>(public val value: T) : Option<T>

    public data object None : Option<Nothing>
}

// pub use crate::lib::ptr;
public object ptr

// pub use crate::lib::result::Result::{self, Err, Ok};
public fun <T> Ok(value: T): Result<T> = Result.success(value)

public fun <T> Err(error: Throwable): Result<T> = Result.failure(error)

// pub use crate::serde_core_private::string::from_utf8_lossy;
public fun fromUtf8Lossy(bytes: ByteArray): String =
    io.github.kotlinmania.serde.core.`private`.fromUtf8Lossy(bytes)

// #[cfg(any(feature = "alloc", feature = "std"))] pub use crate::lib::{ToString, Vec};
//
// The upstream `Vec` resolves to `alloc::vec::Vec` and is re-exported for use by generated code.
// Per the workspace `mod.rs` re-export workflow, this file does not introduce a central `typealias`
// named `Vec`. Callers should reference `kotlin.collections.MutableList` / `kotlin.collections.List`
// directly. If a caller needs to keep the identifier `Vec` unchanged for a faithful translation,
// it should write `import kotlin.collections.MutableList as Vec` in the caller.
//
// Callers migrated:
// - none
=======
// Tracking file for upstream `serde/src/private/mod.rs`. The upstream module is composed of
// submodule declarations (gated on `cfg(not(no_serde_derive))`) and `pub use` re-exports.
//
// Kotlin has no module-level re-export mechanism, so this file:
// - Keeps the upstream module boundary (`io.github.kotlinmania.serde.private`) for callers that
//   want to mirror `serde::__private::...` paths used by derived code.
// - Avoids introducing Kotlin `typealias` shims for standard-library names (Clone, Default,
//   Result, Option, etc.). Kotlin callers use the Kotlin standard library directly.
//
// Upstream `pub mod` lines:
//   `pub mod de;` and `pub mod ser;` — the Kotlin ports live in `De.kt` and `Ser.kt` in this
//   package. These are ported from `serde/src/private/de.rs` and `serde/src/private/ser.rs`.
//
// Upstream `pub use` lines:
//   - `crate::serde_core_private::string::from_utf8_lossy` is surfaced here as a forwarder to the
//     serde_core implementation in `io.github.kotlinmania.serde.core.private`.

public fun fromUtf8Lossy(bytes: ByteArray): String =
    io.github.kotlinmania.serde.core.`private`.fromUtf8Lossy(bytes)

>>>>>>> pr-16-current
