// port-lint: source src/core/lib.rs
package io.github.kotlinmania.serde.core

/*
 * Copyright (c) 2026 Sydney Renee <sydney@solace.ofharmony.ai>
 * and The Solace Project.
 *
 * Licensed under the Apache License, Version 2.0. See LICENSE and NOTICE.
 *
 * This Kotlin source is a port of upstream Serde code, which is licensed
 * under either Apache-2.0 or MIT at your option; see LICENSE-APACHE and
 * LICENSE-MIT.
 */

/**
 * Serde is a framework for ***ser***ializing and ***de***serializing Rust data structures
 * efficiently and generically.
 *
 * The `serde_core` crate contains Serde's trait definitions with **no support for `derive()`**.
 *
 * In crates that derive an implementation of `Serialize` or `Deserialize`, you must depend on the
 * `serde` crate, not `serde_core`.
 *
 * In crates that handwrite implementations of Serde traits, or only use them as trait bounds,
 * depending on `serde_core` is permitted. But `serde` re-exports all of these traits and can be
 * used for this use case too. If in doubt, disregard `serde_core` and always use `serde`.
 *
 * Crates that depend on `serde_core` instead of `serde` are able to compile in parallel with
 * `serde_derive` even when `serde`'s "derive" feature is turned on, as shown in the upstream build
 * timings.
 */
internal object Lib {
    /**
     * Kotlin port note: upstream Serde uses a private `lib` facade module generated by a macro to
     * re-export the subset of `std`, `core`, and `alloc` used throughout the crate. The Kotlin port
     * represents this facade as an object so other ports can import `Lib.Debug`, `Lib.Display`, etc.
     *
     * This is not public API.
     */
    interface Debug

    /**
     * Kotlin port of Rust's `core::fmt::Display` marker in the crate facade.
     *
     * This is not public API.
     */
    interface Display
}

